services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    container_name: nestjs-initializr.backend
    environment:
      PORT: 9901
      GLOBAL_PREFIX: api
      CORS_ORIGIN: http://frontend:3000
      SOCKET_ADMIN_ENABLED: false
    ports:
      - "3001:9901"

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      args:
        - BACKEND_INTERNAL_URL=http://backend:9901
    container_name: nestjs-initializr.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
